version: "3"

services:
  vsftpd:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    restart: always
    ports:
      - "2220:20"
      - "2221:21"
      - "21100-21110:21100-21110"
    volumes:
      - ./home:/home/vsftpd
      - ./logs:/var/log/vsftpd
      - ./cert:/etc/vsftpd/cert
